### ISSUE TITLE
Regeneration is not working

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Bastion#31]
```
[10:36:51 WARN]: [Bastion] Plugin Bastion v2.0.3-1 generated an exception while executing task 307
java.lang.IllegalStateException: Asynchronous entity track!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:104) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:66) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.World.b(World.java:1028) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1127) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1092) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.Chunk.addEntities(Chunk.java:753) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[spigot-1.10.2.jar:git-Spigot-de459a2-5
1263e9]
        at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[spigot-1.10.2.jar:git-Spigot-de459a
2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263
e9]
        at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:129) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getBlockAt(CraftWorld.java:93) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getBlockAt(CraftWorld.java:559) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.Location.getBlock(Location.java:87) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at isaac.bastion.BastionBlock.getReinforcement(BastionBlock.java:276) ~[?:?]
        at isaac.bastion.BastionBlock.regen(BastionBlock.java:202) ~[?:?]
        at isaac.bastion.BastionType$2.run(BastionType.java:391) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by ProgrammerDan** [comment]
Fixed by https://github.com/DevotedMC/Bastion/commit/f31e3b7114c9833bc882f72f10815e84c827d2cc
