### ISSUE TITLE
MySQL Syntax Error on Startup

### ISSUE THREAD

**Issue by fenn96** [DevotedMC/Bastion#55]
I'm getting a MySQL syntax error when trying to use the plugin. **"[Bastion] Migration 1 ] Failed migration: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS bastion_type VARCHAR(40) DEFAULT 'citybastion'' at line 1"**.

My Minecraft version is the latest one, Spigot 1.13.2, but this doesn't seem to be an issue with my Minecraft version. The syntax is wrong in the MySQL.

[21:49:30] [Server thread/INFO]: [Bastion] Enabling Bastion v2.2.3
[21:49:30] [Server thread/INFO]: [Bastion] Loading Bastion type citybastion
[21:49:30] [Server thread/INFO]: [Bastion] Bastion type citybastion loaded: citybastion: LEGACY_NETHER_WART_BLOCK(0) name:City Bastion lore[1]: [This bastion will protect your plot] scale[100->0.2 50cb wm86400000 cd2000 ed0 rd0 iYtrue bte1 doRtrue oDDfalse pearls[false] elytra[true: rMtrue sc1 dobtrue Dobfalse eobtrue eos0.0]
[21:49:30] [Server thread/INFO]: [Bastion] Loading Bastion type claimbastion
[21:49:30] [Server thread/INFO]: [Bastion] Bastion type claimbastion loaded: claimbastion: LEGACY_BONE_BLOCK(0) name:Claim Bastion lore[1]: [This bastion will protect your claims] scale[100->0.2 300r wm86400000 cd2000 ed0 rd0 iYtrue bte1 doRfalse oDDtrue pearls[false] elytra[false]
[21:49:30] [Server thread/INFO]: [Bastion] Loading Bastion type bastion
[21:49:30] [Server thread/INFO]: [Bastion] Bastion type bastion loaded: bastion: LEGACY_SPONGE(0) name:Bastion lore[1]: [this one is hellaz] scale[100->0.2 10r wm86400000 cd2000 ed0 rd0 iYtrue bte1 doRtrue oDDfalse pearls[true: midtrue rMtrue sc2 cobtrue dfBtrue apofalse] elytra[true: rMtrue sc1 dobfalse Dobtrue eobtrue eos0.0]
[21:49:30] [Server thread/INFO]: [Bastion] Preparing to generate ConnectionPool for Bastion.
[21:49:30] [Server thread/INFO]: [Bastion] Connecting to minecraft@localhost:3,306 using root
[21:49:30] [Server thread/WARN]: Wed Mar 13 21:49:30 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[21:49:30] [Server thread/INFO]: [Bastion] Lock acquired, proceeding.
[21:49:30] [Server thread/INFO]: [Bastion] Bastion database is behind, 3 migrations found
[21:49:30] [Server thread/INFO]: [Bastion] Migration 1 ] Applying
[21:49:30] [Server thread/ERROR]: [Bastion] Migration 1 ] Failed migration: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS bastion_type VARCHAR(40) DEFAULT 'citybastion'' at line 1
[21:49:30] [Server thread/ERROR]: [Bastion] Full Error:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS bastion_type VARCHAR(40) DEFAULT 'citybastion'' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120) ~[CivModCore-1.7.0.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[CivModCore-1.7.0.jar:?]
	at vg.civcraft.mc.civmodcore.dao.ManagedDatasource.doMigration(ManagedDatasource.java:359) [CivModCore-1.7.0.jar:?]
	at vg.civcraft.mc.civmodcore.dao.ManagedDatasource.doMigrations(ManagedDatasource.java:323) [CivModCore-1.7.0.jar:?]
	at vg.civcraft.mc.civmodcore.dao.ManagedDatasource.updateDatabase(ManagedDatasource.java:295) [CivModCore-1.7.0.jar:?]
	at isaac.bastion.Bastion.setupDatabase(Bastion.java:93) [Bastion-2.2.3%20(3).jar:?]
	at isaac.bastion.Bastion.onEnable(Bastion.java:40) [Bastion-2.2.3%20(3).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[21:49:30] [Server thread/INFO]: [Bastion] Migration 1 ] Failed.
[21:49:30] [Server thread/WARN]: [Bastion] Bastion failed to apply updates.
[21:49:30] [Server thread/INFO]: [Bastion] Lock released.
[21:49:30] [Server thread/WARN]: [Bastion] Failed to update database, stopping bastion
[21:49:30] [Server thread/INFO]: [Bastion] Disabling Bastion v2.2.3
[21:49:30] [Server thread/ERROR]: Error occurred while disabling Bastion v2.2.3 (Is it up to date?)
java.lang.NullPointerException: null
	at isaac.bastion.Bastion.onDisable(Bastion.java:54) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:423) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at isaac.bastion.Bastion.setupDatabase(Bastion.java:95) [Bastion-2.2.3%20(3).jar:?]
	at isaac.bastion.Bastion.onEnable(Bastion.java:40) [Bastion-2.2.3%20(3).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-3cb9dcb-0f708cb]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by ProgrammerDan** [comment]
Which MySQL version are you running?

**Comment by fenn96** [comment]
5.7.24

**Comment by ProgrammerDan** [comment]
I have successfully forgotten for 3-4 years now to write a MySQL compatible
fork of those migrations, executable on error. We use MariaDB, and some
incompatible commands (like IF NOT EXISTS -- super useful.... but not
available in MySQL) have snuck in. I believe I have another support issue
out here where I wrote alternate code you can run directly on your DB
server to get past this hump. I will attempt to find it today and give it
to you, ping me again later on if you haven't heard from me yet about it.

**Comment by fenn96** [comment]
I tried with MariaDB version 10.3.12 and Bastion worked but NameLayer got this error:

[22:49:39] [Server thread/WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[22:49:39] [Server thread/WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation
[22:49:39] [Server thread/WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[22:49:40] [Server thread/INFO]: [NameLayer:] Info follows
New installation: Welcome to Namelayer!
[22:49:40] [Server thread/INFO]: [NameLayer:] Info follows
Removing any cycles...
[22:49:40] [Server thread/WARN]: [NameLayer] Failed to execute cycle removal code!
[22:49:40] [Server thread/INFO]: [NameLayer] Update prepared, starting database update.
[22:49:40] [Server thread/INFO]: [NameLayer] Lock acquired, proceeding.
[22:49:40] [Server thread/INFO]: [NameLayer] NameLayer database is behind, 15 migrations found
[22:49:40] [Server thread/INFO]: [NameLayer] Migration -1 ] Applying
[22:49:40] [Server thread/INFO]: [NameLayer] Migration -1 ] Successful
[22:49:40] [Server thread/INFO]: [NameLayer] Migration 0 ] Applying
[22:49:40] [Server thread/WARN]: [NameLayer] Migration 0 ] Warning: PROCEDURE minecraft.addplayertotable does not exist
[22:49:40] [Server thread/WARN]: [NameLayer] Migration 0 ] Warning: PROCEDURE minecraft.addplayertotable does not exist
[22:49:40] [Server thread/INFO]: [NameLayer] Migration 0 ] Successful
[22:49:40] [Server thread/INFO]: [NameLayer] Migration 1 ] Applying
[22:49:41] [Server thread/INFO]: [NameLayer] Migration 1 ] Post Call Complete
[22:49:41] [Server thread/INFO]: [NameLayer] Migration 1 ] Successful
[22:49:41] [Server thread/INFO]: [NameLayer] Migration 2 ] Applying
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Can't DROP COLUMN `version`; check that it exists
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Table 'faction_id' already exists
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown column 'name' in 'where clause'
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown column 'faction_name' in 'where clause'
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Table 'minecraft.moderator' doesn't exist
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown column 'name' in 'field list'
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Duplicate column name 'group_name'
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown column 'g.name' in 'field list'
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Can't DROP COLUMN `name`; check that it exists
[22:49:41] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Multiple primary key defined
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown table 'minecraft.personal_group'
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Duplicate column name 'role'
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Duplicate column name 'group_id'
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown column 'fm.faction_name' in 'where clause'
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown column 'fm.faction_name' in 'where clause'
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Can't DROP INDEX `uq_faction_member_1`; check that it exists
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Can't DROP COLUMN `faction_name`; check that it exists
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Table 'minecraft.moderator' doesn't exist
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Unknown table 'minecraft.moderator'
[22:49:42] [Server thread/WARN]: [NameLayer] Migration 2 ] Ignoring error: Duplicate column name 'group_type'
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 2 ] Successful
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 3 ] Applying
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 3 ] Successful
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 4 ] Applying
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 4 ] Successful
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 5 ] Applying
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 5 ] Successful
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 6 ] Applying
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 6 ] Successful
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 7 ] Applying
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 7 ] Successful
[22:49:42] [Server thread/INFO]: [NameLayer] Migration 8 ] Applying
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 8 ] Successful
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 9 ] Applying
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 9 ] Successful
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 10 ] Applying
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 10 ] Successful
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 11 ] Applying
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 11 ] Post Call Complete
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 11 ] Successful
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 12 ] Applying
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 12 ] Successful
[22:49:43] [Server thread/INFO]: [NameLayer] Migration 13 ] Applying
[22:49:43] [Server thread/WARN]: [NameLayer] Migration 13 ] Warning: PROCEDURE minecraft.deletegroupfromtable does not exist
[22:49:43] [Server thread/WARN]: [NameLayer] Migration 13 ] Warning: PROCEDURE minecraft.deletegroupfromtable does not exist
[22:49:43] [Server thread/WARN]: [NameLayer] Migration 13 ] Warning: PROCEDURE minecraft.mergeintogroup does not exist
[22:49:44] [Server thread/WARN]: [NameLayer] Migration 13 ] Warning: PROCEDURE minecraft.mergeintogroup does not exist
[22:49:44] [Server thread/WARN]: [NameLayer] Migration 13 ] Warning: PROCEDURE minecraft.createGroup does not exist
[22:49:44] [Server thread/WARN]: [NameLayer] Migration 13 ] Warning: PROCEDURE minecraft.createGroup does not exist
[22:49:44] [Server thread/INFO]: [NameLayer] Migration 13 ] Successful
[22:49:44] [Server thread/INFO]: [NameLayer] NameLayer fully migrated.
[22:49:44] [Server thread/INFO]: [NameLayer] Lock released.
[22:49:44] [Server thread/INFO]: [NameLayer] Database update took 3 seconds
[22:49:44] [Server thread/WARN]: java.lang.ClassNotFoundException: vg.civcraft.mc.namelayer.misc.v1_13_R2.ProfileModifier
[22:49:44] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[22:49:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134)
[22:49:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80)
[22:49:44] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:49:44] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:49:44] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[22:49:44] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[22:49:44] [Server thread/WARN]: 	at vg.civcraft.mc.namelayer.misc.ClassHandler.Initialize(ClassHandler.java:22)
[22:49:44] [Server thread/WARN]: 	at vg.civcraft.mc.namelayer.NameLayerPlugin.onEnable(NameLayerPlugin.java:58)
[22:49:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[22:49:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[22:49:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[22:49:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[22:49:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[22:49:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[22:49:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[22:49:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[22:49:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[22:49:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[22:49:44] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

It seems when something gets fixed another thing gets broken haha.

**Comment by ProgrammerDan** [comment]
Ahh, you need a 1.13 release, which I have not finalized yet. There is a
largely working version in the mc1.13 branch, but I do not know if you are
comfortable building it yourself. I can get you a build tonight though, if
that would help.

I've held off due to some improvements maxopoly is working, but can def
provide one.

**Comment by fenn96** [comment]
Just wondering how things are going :)
